# https://github.com/stalwartlabs/mail-server/blob/main/resources/config/config.toml

[server.listener."smtp"]
bind = ["[::]:25"]
protocol = "smtp"

[server.listener."submissions"]
bind = ["[::]:465"]
protocol = "smtp"
tls.implicit = true

[server.listener."imaptls"]
bind = ["[::]:993"]
protocol = "imap"
tls.implicit = true

[server.listener."sieve"]
bind = ["[::]:4190"]
protocol = "managesieve"

[server.listener."caddy-aio"]
protocol = "http"
bind = ["[::]:10003"]

[storage]
data = "rocksdb"
fts = "rocksdb"
blob = "rocksdb"
lookup = "rocksdb"
directory = "internal"

[store."rocksdb"]
type = "rocksdb"
path = "/opt/stalwart-mail/data"
compression = "lz4"

[directory."internal"]
type = "internal"
store = "rocksdb"

[tracer."stdout"]
type = "stdout"
level = "info"
ansi = false
enable = true

[lookup."nextcloud-aio"]
domain = "%{env:NC_DOMAIN}%"
hostname = "mail.%{env:NC_DOMAIN}%"

[certificate.nextcloud-aio]
cert = "%{file:/opt/aio-certs/fullchain.crt}%"
default = true
private-key = "%{file:/opt/aio-certs/privkey.key}%"

# [authentication.fallback-admin]
# user = "admin"
# secret = "%{env:ADMIN_SECRET}%"
